const colors = {
  light: {
    text: "#1A0F2E",
    tint: "#5B21B6",
    background: "#FAFAFF",
    foreground: "#1A0F2E",
    card: "#FFFFFF",
    cardForeground: "#1A0F2E",
    primary: "#5B21B6",
    primaryForeground: "#FFFFFF",
    secondary: "#F0EBFF",
    secondaryForeground: "#1A0F2E",
    muted: "#EDE8FA",
    mutedForeground: "#7C6D9A",
    accent: "#F0EBFF",
    accentForeground: "#1A0F2E",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#DDD5F5",
    input: "#DDD5F5",
    gold: "#B8860B",
    goldBright: "#D4AF37",
    success: "#15803D",
    warning: "#B45309",
    surface: "#FFFFFF",
  },
  dark: {
    text: "#F2EEFF",
    tint: "#8B5CF6",
    background: "#0A0714",
    foreground: "#F2EEFF",
    card: "#130D23",
    cardForeground: "#F2EEFF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1435",
    secondaryForeground: "#F2EEFF",
    muted: "#1C1435",
    mutedForeground: "#9E8FC4",
    accent: "#1C1435",
    accentForeground: "#F2EEFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1F52",
    input: "#2D1F52",
    gold: "#D4AA3A",
    goldBright: "#E5C04A",
    success: "#22C55E",
    warning: "#F59E0B",
    surface: "#130D23",
  },
  radius: 12,
};

export default colors;
