uploads = []
outputs = []

[[generated]]
id = "Ni5esFnqHthJ21K2bUeaV"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QYOIX7gYDqaKxGruCIU50"
uri = "file://artifacts/mobile/assets/images/icon_concept.png"
type = "image"
title = "DiGe diamond logo icon"

[[generated]]
id = "h3zLSotUX6T2XBkHKq5qZ"
uri = "file://artifacts/mobile/assets/images/icon_generated.png"
type = "image"
title = "DiGe geometric gem icon"

[[generated]]
id = "Mu4RKZK75RPVOEJCfEoJa"
uri = "file://artifacts/mobile/assets/images/icon_v2.png"
type = "image"
title = "DiGe diamond shield logo"
