import type { JewelryPiece, WishlistItem, InspectionReminder } from "@/context/DiGeContext";

function id() {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
}

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0]!;
}

function daysAgo(days: number): string {
  return daysFromNow(-days);
}

export const DEMO_PIECES: Omit<JewelryPiece, "id" | "createdAt">[] = [
  {
    name: "Tiffany Setting Solitaire Ring",
    type: "ring",
    brand: "Tiffany & Co.",
    material: "Platinum",
    metals: ["Platinum"],
    diamondType: "Natural",
    diamondCaratWeight: "1.52",
    diamondColor: "E",
    diamondClarity: "VS1",
    diamondCut: "Excellent",
    gemstones: [],
    purchaseDate: daysAgo(730),
    purchasePrice: "18500",
    retailer: "Tiffany & Co.",
    serialNumber: "T-2024-0047281",
    goldWarrantyType: "lifetime",
    goldWarrantyNumber: "TIF-LW-2024-4728",
    goldWarrantyExpiry: daysFromNow(1825),
    goldWarrantyDetails:
      "Lifetime warranty covering manufacturing defects. Annual complimentary cleaning included.",
    diamondBondNumber: "DB-TIF-52201",
    diamondBondExpiry: daysFromNow(365),
    diamondBondDetails:
      "Tiffany diamond bond — covers loss, theft, and damage up to appraised value.",
    repairHistory: [],
    documents: [],
    description:
      "Classic six-prong solitaire in platinum. GIA certified, triple excellent cut. Purchased for engagement.",
    lastInspection: daysAgo(180),
    imageUri: undefined,
  },
  {
    name: "Diamond Tennis Bracelet",
    type: "bracelet",
    brand: "Kay Jewelers",
    material: "18K White Gold",
    metals: ["18K White Gold"],
    diamondType: "Natural",
    diamondCaratWeight: "10.00",
    diamondColor: "F",
    diamondClarity: "VS2",
    diamondCut: "Excellent",
    gemstones: [],
    purchaseDate: daysAgo(365),
    purchasePrice: "12800",
    retailer: "Kay Jewelers",
    serialNumber: "KJ-TB-2025-881934",
    goldWarrantyType: "dated",
    goldWarrantyNumber: "KJ-WRN-881934",
    goldWarrantyExpiry: daysFromNow(365),
    goldWarrantyDetails:
      "2-year warranty on clasp, prongs, and setting integrity. Free resizing included.",
    diamondBondNumber: "KJ-DB-881934",
    diamondBondExpiry: daysFromNow(365),
    diamondBondDetails: "Diamond bond covering each stone up to original value.",
    repairHistory: [
      {
        id: id(),
        date: daysAgo(90),
        repairType: "Prong Retipping",
        description: "Re-tipped 3 prongs, professional cleaning",
        cost: "125",
        retailer: "Kay Jewelers",
        createdAt: daysAgo(90),
      },
    ],
    documents: [],
    description:
      "Channel-set 10ct total weight tennis bracelet. 7-inch length. Anniversary gift.",
    lastInspection: daysAgo(90),
    imageUri: undefined,
  },
  {
    name: "Akoya Pearl Strand Necklace",
    type: "necklace",
    brand: "Mikimoto",
    material: "18K White Gold",
    metals: ["18K White Gold"],
    diamondType: undefined,
    gemstones: ["Akoya Pearl"],
    purchaseDate: daysAgo(548),
    purchasePrice: "7200",
    retailer: "Mikimoto",
    serialNumber: "MIK-PN-2024-003821",
    goldWarrantyType: "dated",
    goldWarrantyNumber: "MIK-WRN-003821",
    goldWarrantyExpiry: daysFromNow(180),
    goldWarrantyDetails: "Mikimoto 1-year warranty on clasp and restringing.",
    diamondBondNumber: "",
    diamondBondExpiry: "",
    diamondBondDetails: "",
    repairHistory: [],
    documents: [],
    description:
      "8.5–9mm Akoya cultured pearls, 18-inch strand with 18k white gold diamond-set clasp. Luster grade: Excellent.",
    lastInspection: daysAgo(548),
    imageUri: undefined,
  },
  {
    name: "Submariner Date",
    type: "watch",
    brand: "Rolex",
    material: "Oystersteel",
    metals: ["Oystersteel"],
    watchBand: "Oyster Bracelet",
    watchMovement: "Automatic – Cal. 3235",
    watchCrystal: "Scratch-resistant sapphire",
    watchCase: "40mm Oyster",
    purchaseDate: daysAgo(912),
    purchasePrice: "14800",
    retailer: "Authorized Rolex Dealer",
    serialNumber: "RX-2023-7148205",
    goldWarrantyType: "dated",
    goldWarrantyNumber: "ROL-INT-7148205",
    goldWarrantyExpiry: daysFromNow(913),
    goldWarrantyDetails:
      "5-year international Rolex warranty. Covers manufacturing defects.",
    diamondBondNumber: "",
    diamondBondExpiry: "",
    diamondBondDetails: "",
    repairHistory: [],
    documents: [],
    description:
      "Ref. 126610LN. Black dial, ceramic bezel, 300m waterproof. Box and papers included.",
    lastInspection: daysAgo(912),
    imageUri: undefined,
  },
  {
    name: "Diamond Stud Earrings",
    type: "earrings",
    brand: "Zales",
    material: "18K White Gold",
    metals: ["18K White Gold"],
    diamondType: "Natural",
    diamondCaratWeight: "2.00",
    diamondColor: "G",
    diamondClarity: "SI1",
    diamondCut: "Very Good",
    gemstones: [],
    purchaseDate: daysAgo(200),
    purchasePrice: "4400",
    retailer: "Zales",
    serialNumber: "ZL-ES-2025-220017",
    goldWarrantyType: "lifetime",
    goldWarrantyNumber: "ZL-LTD-220017",
    goldWarrantyExpiry: "",
    goldWarrantyDetails:
      "Zales lifetime diamond guarantee — covers chipping, breaking, and loss from setting.",
    diamondBondNumber: "",
    diamondBondExpiry: "",
    diamondBondDetails: "",
    repairHistory: [],
    documents: [],
    description:
      "1ct each ear, four-prong martini setting, push backs. Classic everyday studs.",
    lastInspection: daysAgo(200),
    imageUri: undefined,
  },
  {
    name: "Ceylon Sapphire Pendant",
    type: "necklace",
    brand: "Blue Nile",
    material: "18K White Gold",
    metals: ["18K White Gold"],
    gemstones: ["Ceylon Sapphire", "Diamond Halo"],
    purchaseDate: daysAgo(420),
    purchasePrice: "3900",
    retailer: "Blue Nile",
    serialNumber: "BN-SP-2024-774102",
    goldWarrantyType: "dated",
    goldWarrantyNumber: "BN-WRN-774102",
    goldWarrantyExpiry: daysFromNow(90),
    goldWarrantyDetails:
      "1-year Blue Nile warranty on setting and chain integrity.",
    diamondBondNumber: "",
    diamondBondExpiry: "",
    diamondBondDetails: "",
    repairHistory: [],
    documents: [],
    description:
      "3.1ct oval Ceylon sapphire, diamond halo, 18-inch cable chain. Royal blue, unheated.",
    lastInspection: daysAgo(420),
    imageUri: undefined,
  },
  {
    name: "Leo Diamond Eternity Band",
    type: "ring",
    brand: "Jared",
    material: "Platinum",
    metals: ["Platinum"],
    diamondType: "Leo Diamond",
    diamondCaratWeight: "2.00",
    diamondColor: "H",
    diamondClarity: "VS2",
    diamondCut: "Excellent",
    gemstones: [],
    purchaseDate: daysAgo(60),
    purchasePrice: "8750",
    retailer: "Jared",
    serialNumber: "JAR-EB-2026-550089",
    goldWarrantyType: "lifetime",
    goldWarrantyNumber: "JAR-LTD-550089",
    goldWarrantyExpiry: "",
    goldWarrantyDetails:
      "Jared lifetime diamond warranty — covers all Leo diamonds in setting.",
    diamondBondNumber: "JAR-DB-550089",
    diamondBondExpiry: daysFromNow(1095),
    diamondBondDetails:
      "Leo Diamond bond — each stone individually tracked and guaranteed.",
    repairHistory: [],
    documents: [],
    description:
      "Full eternity band, 20 Leo diamonds channel set, platinum comfort fit. Anniversary upgrade.",
    lastInspection: daysAgo(60),
    imageUri: undefined,
  },
  {
    name: "Love Bracelet",
    type: "bracelet",
    brand: "Cartier",
    material: "18K Yellow Gold",
    metals: ["18K Yellow Gold"],
    purchaseDate: daysAgo(1095),
    purchasePrice: "7650",
    retailer: "Cartier",
    serialNumber: "CTR-LB-2023-9921047",
    goldWarrantyType: "dated",
    goldWarrantyNumber: "CTR-WRN-9921047",
    goldWarrantyExpiry: daysFromNow(30),
    goldWarrantyDetails:
      "Cartier international 2-year warranty on hardware and finish.",
    diamondBondNumber: "",
    diamondBondExpiry: "",
    diamondBondDetails: "",
    repairHistory: [
      {
        id: id(),
        date: daysAgo(300),
        repairType: "Polish & Inspection",
        description: "Polishing and hardware inspection",
        cost: "0",
        retailer: "Cartier",
        createdAt: daysAgo(300),
      },
    ],
    documents: [],
    description:
      "Classic yellow gold Love bracelet, size 17. Comes with original screwdriver. Iconic gift.",
    lastInspection: daysAgo(300),
    imageUri: undefined,
  },
];

export const DEMO_WISHLIST: Omit<WishlistItem, "id" | "createdAt">[] = [
  {
    name: "Open Heart Diamond Pendant",
    sku: "KJ-OHP-82241",
    type: "necklace",
    brand: "Kay Jewelers",
    retailer: "Kay Jewelers",
    retailerUrl: "https://www.kay.com",
    estimatedPrice: "1850",
    notes: "18k white gold, 0.50ct center diamond. Perfect gift idea.",
    priority: "high",
    imageUrl: undefined,
  },
  {
    name: "Diamond Tennis Necklace",
    sku: "ZL-DTN-441090",
    type: "necklace",
    brand: "Zales",
    retailer: "Zales",
    retailerUrl: "https://www.zales.com",
    estimatedPrice: "6400",
    notes: "5ct total weight, 18 inches, white gold. Matches my tennis bracelet.",
    priority: "medium",
    imageUrl: undefined,
  },
  {
    name: "Pearl Drop Earrings",
    sku: "MIK-PE-7742",
    type: "earrings",
    brand: "Mikimoto",
    retailer: "Mikimoto",
    retailerUrl: "https://www.mikimoto.com",
    estimatedPrice: "3200",
    notes: "9mm Akoya pearls with diamond accents. Pairs with my pearl strand.",
    priority: "low",
    imageUrl: undefined,
  },
  {
    name: "Pavé Diamond Hoop Earrings",
    sku: "BN-PHE-229017",
    type: "earrings",
    brand: "Blue Nile",
    retailer: "Blue Nile",
    retailerUrl: "https://www.bluenile.com",
    estimatedPrice: "2100",
    notes: "Medium size, 18k white gold, inside-out pave. Everyday wearable.",
    priority: "high",
    imageUrl: undefined,
  },
];

export const DEMO_REMINDERS: Omit<InspectionReminder, "id" | "createdAt">[] = [
  {
    jewelryName: "Tiffany Setting Solitaire Ring",
    retailer: "Tiffany & Co.",
    scheduledDate: daysFromNow(14),
    recurrence: "1year",
    notes:
      "Annual prong check and professional cleaning. Book appointment at Tiffany boutique.",
    isCompleted: false,
    notificationId: undefined,
  },
  {
    jewelryName: "Submariner Date",
    retailer: "Authorized Rolex Dealer",
    scheduledDate: daysFromNow(45),
    recurrence: "2years",
    notes:
      "Full service due — movement cleaning, gasket replacement, pressure test.",
    isCompleted: false,
    notificationId: undefined,
  },
  {
    jewelryName: "Love Bracelet",
    retailer: "Cartier",
    scheduledDate: daysFromNow(30),
    recurrence: "2years",
    notes: "Warranty renewal and annual inspection at Cartier boutique.",
    isCompleted: false,
    notificationId: undefined,
  },
  {
    jewelryName: "Diamond Tennis Bracelet",
    retailer: "Kay Jewelers",
    scheduledDate: daysFromNow(72),
    recurrence: "6months",
    notes:
      "6-month prong and clasp check. Last visit found 3 worn prongs.",
    isCompleted: false,
    notificationId: undefined,
  },
];
